import Link from 'next/link';

export default function AdmissionsPage() {
  const programmes = [
    { name: 'Computer Physical Education', seats: 120, duration: '3 Years', icon: '💻' },
    { name: 'Civil Physical Education', seats: 60, duration: '3 Years', icon: '🏗️' },
    { name: 'Mechanical Physical Education', seats: 60, duration: '3 Years', icon: '⚙️' },
    { name: 'Information Technology', seats: 60, duration: '3 Years', icon: '🔧' },
    { name: 'Bachelor of Business Administration', seats: 120, duration: '3 Years', icon: '📊' },
  ];
  return <div>
    <div className="bg-gray-100 py-4 border-b"><div className="max-w-7xl mx-auto px-4 flex items-center gap-2 text-sm text-gray-600"><Link href="/" className="hover:text-blue-600">Home</Link><span>/</span><span className="text-gray-900 font-medium">Admissions</span></div></div>
    <section className="bg-gradient-to-r from-blue-900 to-blue-700 text-white py-20"><div className="max-w-7xl mx-auto px-4"><h1 className="text-5xl font-bold mb-4">Admissions 2026-27</h1><p className="text-xl text-blue-100 mb-6">Shape Your Future with Noble Institute of Physical Education</p><div className="flex flex-wrap gap-4"><Link href="#programmes" className="bg-yellow-400 text-blue-900 px-8 py-3 rounded-lg font-bold hover:bg-yellow-300 transition">Explore Programmes</Link><Link href="#contact" className="border-2 border-white px-8 py-3 rounded-lg font-bold hover:bg-white hover:text-blue-900 transition">Contact Admission Cell</Link></div></div></section>
    <section className="py-16"><div className="max-w-7xl mx-auto px-4"><h2 className="text-3xl font-bold text-blue-900 mb-8 text-center">Eligibility Criteria</h2><div className="grid md:grid-cols-2 gap-8"><div className="bg-white rounded-xl p-6 shadow-lg border-t-4 border-blue-500"><h3 className="text-xl font-bold text-blue-900 mb-4">Diploma Physical Education</h3><ul className="space-y-3 text-gray-700"><li>• Minimum 10th Standard Pass (SSC)</li><li>• Valid Gujarat CET/ACPDC score</li><li>• Contact: +91-92654-63335 & +91-92654-15454</li></ul></div><div className="bg-white rounded-xl p-6 shadow-lg border-t-4 border-yellow-500"><h3 className="text-xl font-bold text-blue-900 mb-4">Direct Admission</h3><ul className="space-y-3 text-gray-700"><li>• Management quota seats available</li><li>• Vacant quota seats available</li><li>• Contact admission cell for details</li><li>• 100% Free Scholarships available for SC/ST students</li><li>• Advanced Labs and Experienced Faculty</li></ul></div></div></div></section>
    <section id="programmes" className="py-16 bg-gray-50"><div className="max-w-7xl mx-auto px-4"><div className="text-center mb-10"><h2 className="text-3xl font-bold text-blue-900">Available Programmes</h2><p className="mt-2 text-gray-600">Explore programmes and current intake capacity before applying.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-6">{programmes.map((program) => <div key={program.name} className="bg-white rounded-xl p-6 shadow-lg hover:shadow-xl hover:-translate-y-1 transition-all border-2 border-transparent hover:border-yellow-400"><div className="text-5xl mb-4">{program.icon}</div><h3 className="text-lg font-bold text-blue-900 mb-2">{program.name}</h3><div className="space-y-1 text-sm text-gray-600"><p>Duration: {program.duration}</p><p className="font-semibold text-blue-700">Intake: {program.seats} seats</p></div><Link href="/courses" className="mt-4 block w-full text-center bg-blue-600 text-white py-2 rounded-lg hover:bg-blue-700 transition">View Programme</Link></div>)}</div></div></section>
    <section className="py-16"><div className="max-w-7xl mx-auto px-4"><h2 className="text-3xl font-bold text-blue-900 mb-8 text-center">Admission Process</h2><div className="bg-white rounded-xl p-8 shadow-lg max-w-3xl mx-auto"><div className="bg-blue-50 border-l-4 border-blue-500 p-6 rounded mb-6"><h3 className="text-xl font-bold text-blue-900 mb-2">ACPDC Portal</h3><p className="text-gray-700">Candidates applying for diploma programmes should register and apply through the official ACPDC process.</p></div><div className="space-y-4">{['Register on ACPDC Portal','Document Verification','Merit List & Counseling','Seat Allotment & Admission'].map((step, index) => <div key={step} className="flex items-start gap-4 p-4 bg-gray-50 rounded-lg"><div className="w-10 h-10 bg-blue-600 text-white rounded-full flex items-center justify-center font-bold flex-shrink-0">{index + 1}</div><div><h3 className="font-bold text-blue-900">{step}</h3><p className="text-gray-600 text-sm">Complete the required step with the admission cell guidance.</p></div></div>)}</div></div></div></section>
    <section className="py-16 bg-blue-50"><div className="max-w-7xl mx-auto px-4"><h2 className="text-3xl font-bold text-blue-900 mb-8 text-center">Fee Structure</h2><div className="bg-white rounded-xl p-8 shadow-lg max-w-3xl mx-auto"><div className="grid md:grid-cols-3 gap-6 mb-6"><div className="text-center p-4 bg-blue-100 rounded-lg"><div className="text-3xl font-bold text-blue-900">₹18,900</div><div className="text-sm text-gray-600">Per Semester</div></div><div className="text-center p-4 bg-blue-100 rounded-lg"><div className="text-3xl font-bold text-blue-900">₹37,800</div><div className="text-sm text-gray-600">Per Annum</div></div><div className="text-center p-4 bg-yellow-100 rounded-lg"><div className="text-3xl font-bold text-blue-900">₹1,13,400</div><div className="text-sm text-gray-600">Total (3 Years)</div></div></div><div className="bg-green-50 border-l-4 border-green-400 p-4 rounded"><p className="text-gray-700"><strong>Scholarship:</strong> 100% scholarship available for ST/SC category students as per government norms.</p></div></div></div></section>
    <section className="py-16"><div className="max-w-7xl mx-auto px-4"><h2 className="text-3xl font-bold text-blue-900 mb-8 text-center">Documents Required</h2><div className="bg-white rounded-xl p-8 shadow-lg"><div className="grid md:grid-cols-2 gap-4">{['10th Marksheet (SSC)','12th Marksheet (HSC)','School Leaving Certificate','Caste Certificate (if applicable)','Income Certificate (if applicable)','Aadhar Card','Passport Size Photos (4)','Gujarat CET/ACPC Allotment Letter'].map((doc) => <div key={doc} className="flex items-center gap-3 p-3 bg-gray-50 rounded-lg"><span className="text-green-500">✓</span><span className="text-gray-700">{doc}</span></div>)}</div></div></div></section>
    <section id="contact" className="py-16 bg-blue-900 text-white"><div className="max-w-7xl mx-auto px-4 text-center"><h2 className="text-3xl font-bold mb-4">Need Help?</h2><p className="text-blue-100 mb-6">Contact our admission cell for any queries.</p><div className="flex flex-wrap justify-center gap-8"><span>📞 +91-92654-63335</span><span>📞 +91-92654-15454</span><span>✉️ nobleinstituteoftechnology2025@gmail.com</span></div></div></section>
  </div>;
}
