import Link from 'next/link';

export default function CoursesPage() {
  const courses = [
    { name: 'B.P.Ed.', code: 'CE', duration: '3 Years', seats: 120, description: 'Learn programming, software development, networking, and emerging technologies in B.P.Ed..', icon: '💻', subjects: ['Programming in C', 'Data Structures', 'Database Management', 'Web Development', 'Software Physical Education', 'Network Security'], career: ['Software Developer', 'Network Engineer', 'Database Administrator', 'Web Developer', 'System Analyst'] },
    { name: 'B.P.Ed.', code: 'CV', duration: '3 Years', seats: 60, description: 'Master construction technology, structural Physical Education, and infrastructure development.', icon: '🏗️', subjects: ['Physical Education Drawing', 'Building Materials', 'Surveying', 'Structural Analysis', 'Construction Management', 'AutoCAD'], career: ['Civil Engineer', 'Site Engineer', 'Structural Engineer', 'Construction Manager', 'Surveyor'] },
    { name: 'Mechanical Physical Education', code: 'ME', duration: '3 Years', seats: 60, description: 'Explore manufacturing processes, automation, mechanical systems, and industrial Physical Education.', icon: '⚙️', subjects: ['Physical Education Mechanics', 'Thermodynamics', 'Manufacturing Process', 'Machine Design', 'CAD/CAM', 'Industrial Automation'], career: ['Mechanical Engineer', 'Production Engineer', 'Design Engineer', 'Maintenance Engineer', 'Quality Control'] },
    { name: 'B.P.Ed.', code: 'IT', duration: '3 Years', seats: 60, description: 'Study networks, cybersecurity, IT infrastructure, and information systems management.', icon: '🔧', subjects: ['Computer Networks', 'Cybersecurity', 'Cloud Computing', 'System Administration', 'IT Infrastructure', 'DevOps'], career: ['Network Administrator', 'Security Analyst', 'System Administrator', 'Cloud Engineer', 'IT Support'] },
    { name: 'Bachelor of Physical Education', code: 'B.P.Ed.', duration: '4 Years', seats: 120, description: 'Build strong foundations in business, management, entrepreneurship, finance, marketing, and leadership.', icon: '📊', subjects: ['Principles of Management', 'Financial Management', 'Marketing Management', 'Human Resource Management', 'Business Analytics', 'Entrepreneurship'], career: ['Business Executive', 'Marketing Executive', 'HR Executive', 'Business Analyst', 'Entrepreneur'] },
  ];

  return <div>
    <div className="bg-gray-100 py-4 border-b"><div className="max-w-7xl mx-auto px-4 flex items-center gap-2 text-sm text-gray-600"><Link href="/" className="hover:text-blue-600">Home</Link><span>/</span><span className="text-gray-900 font-medium">Courses</span></div></div>
    <section className="bg-gradient-to-r from-blue-900 to-blue-700 text-white py-20"><div className="max-w-7xl mx-auto px-4"><h1 className="text-5xl font-bold mb-4">Our Programmes</h1><p className="text-xl text-blue-100">Explore programmes and begin your admission application online.</p></div></section>
    <section className="py-16"><div className="max-w-7xl mx-auto px-4"><div className="grid md:grid-cols-2 gap-8">{courses.map((course) => <div key={course.code} className="bg-white rounded-xl shadow-lg overflow-hidden hover:shadow-xl transition"><div className="bg-gradient-to-r from-blue-600 to-blue-800 text-white p-6"><div className="flex items-center justify-between gap-4"><div><span className="text-5xl">{course.icon}</span><h2 className="text-2xl font-bold mt-2">{course.name}</h2><p className="text-blue-200">Code: {course.code}</p></div><div className="text-right"><div className="text-3xl font-bold">{course.seats}</div><div className="text-sm text-blue-200">Seats</div></div></div></div><div className="p-6"><p className="text-gray-700 mb-4">{course.description}</p><div className="mb-4"><h3 className="font-bold text-blue-900 mb-2">Duration</h3><p className="text-gray-600">{course.duration}</p></div><div className="mb-4"><h3 className="font-bold text-blue-900 mb-2">Key Subjects</h3><div className="flex flex-wrap gap-2">{course.subjects.map((subject) => <span key={subject} className="bg-blue-100 text-blue-800 px-3 py-1 rounded-full text-sm">{subject}</span>)}</div></div><div className="mb-6"><h3 className="font-bold text-blue-900 mb-2">Career Opportunities</h3><div className="flex flex-wrap gap-2">{course.career.map((career) => <span key={career} className="bg-yellow-100 text-yellow-800 px-3 py-1 rounded-full text-sm">{career}</span>)}</div></div><Link href={`/admissions/apply?course=${encodeURIComponent(course.name)}`} className="block w-full text-center bg-yellow-400 text-blue-900 py-3 rounded-lg font-bold hover:bg-yellow-300 transition">Apply for {course.code}</Link></div></div>)}</div></div></section>
    <section className="py-16 bg-gray-50"><div className="max-w-7xl mx-auto px-4"><h2 className="text-3xl font-bold text-blue-900 mb-8 text-center">Why Choose Noble?</h2><div className="grid md:grid-cols-3 gap-6"><div className="bg-white p-6 rounded-xl shadow-lg text-center"><div className="text-4xl mb-4">🎓</div><h3 className="text-xl font-bold text-blue-900 mb-2">Industry-Ready Curriculum</h3><p className="text-gray-600">Updated learning aligned with practical skills, industry requirements and emerging technologies.</p></div><div className="bg-white p-6 rounded-xl shadow-lg text-center"><div className="text-4xl mb-4">🏢</div><h3 className="text-xl font-bold text-blue-900 mb-2">Student-Focused Campus</h3><p className="text-gray-600">A learning environment designed around academic growth, practical exposure and student development.</p></div><div className="bg-white p-6 rounded-xl shadow-lg text-center"><div className="text-4xl mb-4">🔬</div><h3 className="text-xl font-bold text-blue-900 mb-2">Modern Infrastructure</h3><p className="text-gray-600">Labs, library and facilities that support practical learning and academic activities.</p></div></div></div></section>
  </div>;
}
