import Link from 'next/link';

const courses = [
  { name: 'B.P.Ed.', code: 'CE', duration: '3 Years', seats: 120, icon: '💻', description: 'Learn programming, software development, networking, and emerging technologies in B.P.Ed..', subjects: ['Programming in C', 'Data Structures', 'Database Management', 'Web Development', 'Software Physical Education', 'Network Security'], career: ['Software Developer', 'Network Engineer', 'Database Administrator', 'Web Developer', 'System Analyst'] },
  { name: 'B.P.Ed.', code: 'CV', duration: '3 Years', seats: 60, icon: '🏗️', description: 'Master construction technology, structural Physical Education, and infrastructure development.', subjects: ['Physical Education Drawing', 'Building Materials', 'Surveying', 'Structural Analysis', 'Construction Management', 'AutoCAD'], career: ['Civil Engineer', 'Site Engineer', 'Structural Engineer', 'Construction Manager', 'Surveyor'] },
  { name: 'Mechanical Physical Education', code: 'ME', duration: '3 Years', seats: 60, icon: '⚙️', description: 'Explore manufacturing processes, automation, mechanical systems, and industrial Physical Education.', subjects: ['Physical Education Mechanics', 'Thermodynamics', 'Manufacturing Process', 'Machine Design', 'CAD/CAM', 'Industrial Automation'], career: ['Mechanical Engineer', 'Production Engineer', 'Design Engineer', 'Maintenance Engineer', 'Quality Control'] },
  { name: 'B.P.Ed.', code: 'IT', duration: '3 Years', seats: 60, icon: '🔧', description: 'Study networks, cybersecurity, IT infrastructure, and information systems management.', subjects: ['Computer Networks', 'Cybersecurity', 'Cloud Computing', 'System Administration', 'IT Infrastructure', 'DevOps'], career: ['Network Administrator', 'Security Analyst', 'System Administrator', 'Cloud Engineer', 'IT Support'] },
  { name: 'Bachelor of Physical Education', code: 'B.P.Ed.', duration: '4 Years', seats: 120, icon: '📊', description: 'Build practical business, management, leadership, finance, marketing, and entrepreneurship skills for modern careers.', subjects: ['Principles of Management', 'Financial Accounting', 'Marketing Management', 'Human Resource Management', 'Business Economics', 'Entrepreneurship'], career: ['Business Manager', 'Marketing Executive', 'HR Executive', 'Financial Analyst', 'Entrepreneur'] },
];

export default function CoursesProgrammesPage() {
  return <div>
    <div className="bg-gray-100 py-4 border-b"><div className="max-w-7xl mx-auto px-4 flex items-center gap-2 text-sm text-gray-600"><Link href="/" className="hover:text-blue-600">Home</Link><span>/</span><span className="text-gray-900 font-medium">Courses</span></div></div>
    <section className="bg-gradient-to-r from-blue-900 to-blue-700 text-white py-16 sm:py-20"><div className="max-w-7xl mx-auto px-4"><h1 className="text-4xl sm:text-5xl font-bold mb-4">Our Programmes</h1><p className="text-lg sm:text-xl text-blue-100">Explore our career-focused programmes and available intake.</p></div></section>
    <section className="py-12 sm:py-16"><div className="max-w-7xl mx-auto px-4"><div className="grid md:grid-cols-2 gap-6 sm:gap-8">{courses.map(course => <article key={course.code} className="bg-white rounded-2xl shadow-lg overflow-hidden hover:shadow-2xl transition-shadow"><div className="bg-gradient-to-r from-blue-600 to-blue-800 text-white p-5 sm:p-6"><div className="flex items-start justify-between gap-4"><div><span className="text-4xl sm:text-5xl">{course.icon}</span><h2 className="text-xl sm:text-2xl font-bold mt-2">{course.name}</h2><p className="text-blue-200">Code: {course.code}</p></div><div className="text-right shrink-0"><div className="text-2xl sm:text-3xl font-bold">{course.seats}</div><div className="text-sm text-blue-200">Seats</div></div></div></div><div className="p-5 sm:p-6"><p className="text-gray-700 mb-5">{course.description}</p><div className="mb-4"><h3 className="font-bold text-blue-900 mb-2">Duration</h3><p className="text-gray-600">{course.duration}</p></div><div className="mb-5"><h3 className="font-bold text-blue-900 mb-2">Key Subjects</h3><div className="flex flex-wrap gap-2">{course.subjects.map(s => <span key={s} className="bg-blue-100 text-blue-800 px-3 py-1 rounded-full text-sm">{s}</span>)}</div></div><div className="mb-6"><h3 className="font-bold text-blue-900 mb-2">Career Opportunities</h3><div className="flex flex-wrap gap-2">{course.career.map(c => <span key={c} className="bg-yellow-100 text-yellow-800 px-3 py-1 rounded-full text-sm">{c}</span>)}</div></div>{course.code === 'B.P.Ed.' ? <Link href="/courses/B.P.Ed." className="block w-full text-center bg-yellow-400 text-blue-900 py-3 rounded-lg font-bold hover:bg-yellow-300 transition">View B.P.Ed. Programme</Link> : <Link href="/admissions" className="block w-full text-center bg-yellow-400 text-blue-900 py-3 rounded-lg font-bold hover:bg-yellow-300 transition">Apply for {course.code}</Link>}</div></article>)}</div></div></section>
    <section className="py-12 sm:py-16 bg-gray-50"><div className="max-w-7xl mx-auto px-4"><h2 className="text-3xl font-bold text-blue-900 mb-8 text-center">Why Choose Noble?</h2><div className="grid md:grid-cols-3 gap-6"><div className="bg-white p-6 rounded-xl shadow-lg text-center"><div className="text-4xl mb-4">🎓</div><h3 className="text-xl font-bold text-blue-900 mb-2">Industry-Ready Curriculum</h3><p className="text-gray-600">Updated syllabus aligned with industry requirements and emerging technologies.</p></div><div className="bg-white p-6 rounded-xl shadow-lg text-center"><div className="text-4xl mb-4">🏢</div><h3 className="text-xl font-bold text-blue-900 mb-2">Placement Focus</h3><p className="text-gray-600">Career-oriented learning and opportunities for students to prepare for industry.</p></div><div className="bg-white p-6 rounded-xl shadow-lg text-center"><div className="text-4xl mb-4">🔬</div><h3 className="text-xl font-bold text-blue-900 mb-2">Modern Infrastructure</h3><p className="text-gray-600">Labs, library, and facilities designed to support practical learning.</p></div></div></div></section>
  </div>;
}
