CREATE TABLE "AdmissionApplication" (
  "id" TEXT NOT NULL,
  "applicationNumber" TEXT NOT NULL,
  "publicToken" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "age" INTEGER NOT NULL,
  "phone" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "preferredCourse" TEXT NOT NULL,
  "caste" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "ipAddress" TEXT,
  "userAgent" TEXT,
  "casteCertificate" BYTEA,
  "casteCertificateName" TEXT,
  "casteCertificateMime" TEXT,
  "tenthMarksheet" BYTEA,
  "tenthMarksheetName" TEXT,
  "tenthMarksheetMime" TEXT,
  "twelfthMarksheet" BYTEA,
  "twelfthMarksheetName" TEXT,
  "twelfthMarksheetMime" TEXT,
  "schoolLeaving" BYTEA,
  "schoolLeavingName" TEXT,
  "schoolLeavingMime" TEXT,
  "incomeCertificate" BYTEA,
  "incomeCertificateName" TEXT,
  "incomeCertificateMime" TEXT,
  "aadharCard" BYTEA,
  "aadharCardName" TEXT,
  "aadharCardMime" TEXT,
  "passportPhoto1" BYTEA,
  "passportPhoto1Name" TEXT,
  "passportPhoto1Mime" TEXT,
  "passportPhoto2" BYTEA,
  "passportPhoto2Name" TEXT,
  "passportPhoto2Mime" TEXT,
  "passportPhoto3" BYTEA,
  "passportPhoto3Name" TEXT,
  "passportPhoto3Mime" TEXT,
  "passportPhoto4" BYTEA,
  "passportPhoto4Name" TEXT,
  "passportPhoto4Mime" TEXT,
  "allotmentLetter" BYTEA,
  "allotmentLetterName" TEXT,
  "allotmentLetterMime" TEXT,
  "nonCreamyLayer" BYTEA,
  "nonCreamyLayerName" TEXT,
  "nonCreamyLayerMime" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "AdmissionApplication_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "AdmissionApplication_applicationNumber_key" ON "AdmissionApplication"("applicationNumber");
CREATE UNIQUE INDEX "AdmissionApplication_publicToken_key" ON "AdmissionApplication"("publicToken");
CREATE INDEX "AdmissionApplication_status_createdAt_idx" ON "AdmissionApplication"("status", "createdAt");
CREATE INDEX "AdmissionApplication_email_idx" ON "AdmissionApplication"("email");
CREATE INDEX "AdmissionApplication_phone_idx" ON "AdmissionApplication"("phone");
