import Link from 'next/link';

export default function BBACoursePage() {
  return <main className="min-h-screen bg-gray-50">
    <section className="bg-gradient-to-r from-blue-900 to-blue-700 py-20 text-white"><div className="mx-auto max-w-5xl px-4"><p className="mb-3 text-sm font-semibold uppercase tracking-[0.2em] text-yellow-300">Undergraduate Programme</p><h1 className="text-4xl font-bold md:text-5xl">Bachelor of Physical Education</h1><p className="mt-4 max-w-2xl text-lg text-blue-100">A sports-focused undergraduate programme designed to build practical physical education and professional skills.</p></div></section>
    <section className="mx-auto grid max-w-5xl gap-6 px-4 py-12 md:grid-cols-3"><div className="rounded-2xl bg-white p-6 text-center shadow-lg"><div className="text-4xl font-bold text-blue-900">B.P.Ed.</div><p className="mt-2 text-gray-500">Programme</p></div><div className="rounded-2xl bg-white p-6 text-center shadow-lg"><div className="text-4xl font-bold text-blue-900">120</div><p className="mt-2 text-gray-500">Intake Seats</p></div><div className="rounded-2xl bg-white p-6 text-center shadow-lg"><div className="text-4xl font-bold text-blue-900">4 Years</div><p className="mt-2 text-gray-500">Duration</p></div></section>
    <section className="mx-auto max-w-5xl px-4 pb-16"><div className="rounded-2xl bg-white p-8 shadow-lg"><h2 className="text-2xl font-bold text-blue-900">Programme Overview</h2><p className="mt-4 leading-7 text-gray-600">The B.P.Ed. programme provides students with a foundation in Physical Education, physical education, marketing, finance and human resources, while developing professional communication and leadership skills.</p><div className="mt-8 flex flex-wrap gap-3"><span className="rounded-full bg-blue-100 px-4 py-2 text-sm text-blue-800">sports physical education</span><span className="rounded-full bg-blue-100 px-4 py-2 text-sm text-blue-800">Marketing</span><span className="rounded-full bg-blue-100 px-4 py-2 text-sm text-blue-800">Finance</span><span className="rounded-full bg-blue-100 px-4 py-2 text-sm text-blue-800">Human Resources</span></div><div className="mt-8 flex flex-wrap gap-3"><Link href="/admissions/apply?course=Bachelor%20of%20sports%20Administration" className="rounded-lg bg-yellow-400 px-6 py-3 font-bold text-blue-900 hover:bg-yellow-300">Apply Now</Link><Link href="/courses" className="rounded-lg border border-blue-900 px-6 py-3 font-bold text-blue-900 hover:bg-blue-50">All Programmes</Link></div></div></section>
  </main>;
}
